// writes the SYNAPSE brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#14f195"/><stop offset="1" stop-color="#dc1fff"/></linearGradient></defs><circle cx="20" cy="20" r="18" fill="none" stroke="url(#lg)" stroke-width="3"/><circle cx="20" cy="20" r="9" fill="url(#lg)"/><path d="M20 2v6M20 32v6M2 20h6M32 20h6" stroke="#f1eefa" stroke-width="2" stroke-linecap="round"/></svg>`;
const wave = (w, h, seed, color) => { let d = 'M0 ' + h * .55; let y = h * .55; for (let x = 0; x <= w; x += w / 60) { y += (Math.sin(x / (w / 9) + seed) * .6 + Math.sin(x / (w / 23) + seed * 2) * .4) * -h * .05 - h * .002; y = Math.max(h * .12, Math.min(h * .9, y)); d += ' L' + x.toFixed(0) + ' ' + y.toFixed(1); } return `<svg viewBox="0 0 ${w} ${h}" style="width:${w}px;height:${h}px;position:absolute;left:0;top:0"><path d="${d}" fill="none" stroke="${color}" stroke-width="4" stroke-linejoin="round" style="filter:drop-shadow(0 0 10px ${color})"/></svg>`; };
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#776e8f;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#b3aac9}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#f1eefa;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}.card{background:#0c0a14dd;box-shadow:inset 0 0 0 1px #2e2646;position:relative;overflow:hidden}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}SYNAPSE</b><span>synapsepad.xyz · @synapsepad · Solana</span></div>`;

fs.writeFileSync(path.join(S, 'synapse-pfp.html'), `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2000px;height:2000px;display:grid;place-items:center}</style><body><div class="amb" style="opacity:.55"></div>${mark(1150)}`);
fs.writeFileSync(path.join(S, 'synapse-banner.html'), `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:3000px;height:1000px}h1{position:absolute;left:190px;top:250px;font-family:Michroma;font-weight:400;font-size:150px;line-height:1.15;text-transform:uppercase}p{position:absolute;left:198px;bottom:150px;font-family:Sora;font-weight:300;font-size:44px;letter-spacing:.08em;color:#b3aac9}.m{position:absolute;right:300px;top:240px}</style><body><div class="amb"></div><h1>Memecoins<br>with a <span class="iri">brain.</span></h1><p>SYNAPSE · launch a coin that earns, trades and funds itself · synapsepad.xyz</p><div class="m">${mark(520)}</div>`);

fs.writeFileSync(path.join(S, 'synapse-keyart.html'), page(`<div class="pad"><div class="kick">launchpad · Solana</div><h1 style="font-size:128px;margin-top:70px">Memecoins<br>with a <span class="iri">brain.</span></h1><p style="font-size:42px;color:#b3aac9;max-width:1250px;margin-top:60px;line-height:1.6">Launch a coin and it gets a treasury, a brain and a trading desk. <b style="color:#f1eefa;font-weight:500">Profits buy the coin back.</b></p></div><div class="card cut" style="position:absolute;right:130px;top:560px;width:820px;height:440px">${wave(820, 440, 1.3, '#14f195')}<div style="position:absolute;left:30px;top:24px;font-family:Michroma;font-size:18px;letter-spacing:.24em;color:#776e8f">WARD · LIVE EQUITY</div><div style="position:absolute;right:30px;bottom:22px;font-size:40px;font-weight:500;color:#14f195">+38.4%</div></div>`));

const steps = [['01', 'Launch', 'Name, ticker, brain, seed SOL. The seed becomes the agent treasury and the coin lists on a bonding curve.'], ['02', 'Earn', 'Every buy and sell of the coin pays 1%. Half lands in the agent treasury as cash to trade with.'], ['03', 'Trade', 'The brain reads the live tape every 5 seconds: SOL, BTC, ETH, DOGE, TSLA, NVDA, SPY and more. Every decision is logged with its reasoning.'], ['04', 'Fund itself', 'When the agent beats its high-water mark, half the gain buys the coin on the curve. Trading skill becomes buy pressure.']];
fs.writeFileSync(path.join(S, 'synapse-howitworks.html'), page(`<div class="pad"><div class="kick">how a coin gets a brain</div><h1 style="font-size:96px;margin-top:40px">Launch. Earn. Trade. <span class="iri">Fund itself.</span></h1><div class="g">${steps.map((s) => `<div class="card cut s"><div class="n">${s[0]}</div><h2>${s[1]}</h2><p>${s[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:28px;margin-top:80px}.s{padding:48px 40px;height:560px}.n{font-family:Michroma;font-size:28px;color:#14f195}.s h2{font-family:Michroma;font-weight:400;font-size:52px;text-transform:uppercase;margin:30px 0 26px}.s p{font-size:29px;line-height:1.6;color:#b3aac9}`));

const brains = [['Momentum', '#14f195', 'Buys what is already moving. Rides winners, cuts losers.'], ['Mean reversion', '#dc1fff', 'Buys what just fell, sells what just spiked.'], ['Trend', '#c7b3ff', 'Only holds names above their 30-day trend. Patient.'], ['Degen', '#ffb36b', 'Crypto only. Max size. Flips on every 24h move.'], ['Hedge', '#ffe27b', 'Long the strongest, short the weakest, dollar-neutral.'], ['Vol hunter', '#5ad8ff', 'Goes where the volatility is. Small size, many names.']];
fs.writeFileSync(path.join(S, 'synapse-brains.html'), page(`<div class="pad"><div class="kick">six brains</div><h1 style="font-size:96px;margin-top:40px">Pick a brain. <span class="iri">Or let the ward rank it.</span></h1><div class="g">${brains.map((b, i) => `<div class="card cut b" style="height:330px">${wave(690, 330, i + .7, b[1])}<div style="position:absolute;left:36px;top:30px;display:flex;align-items:center;gap:16px"><i style="width:18px;height:18px;border-radius:50%;background:${b[1]};box-shadow:0 0 18px ${b[1]}"></i><h2>${b[0]}</h2></div><p>${b[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:28px;margin-top:70px}.b h2{font-family:Michroma;font-weight:400;font-size:34px;text-transform:uppercase}.b p{position:absolute;left:36px;right:36px;bottom:30px;font-size:26px;line-height:1.5;color:#f1eefa;background:#07060ccc;padding:12px 14px}`));

fs.writeFileSync(path.join(S, 'synapse-ward.html'), page(`<div class="pad"><div class="kick">the ward</div><h1 style="font-size:96px;margin-top:40px">Every agent. <span class="iri">Ranked live.</span></h1><div class="card cut" style="margin-top:60px;height:640px;padding:40px 48px"><div style="display:flex;justify-content:space-between;font-family:Michroma;font-size:18px;letter-spacing:.24em;color:#776e8f">WARD · LIVE EQUITY · ALL AGENTS<span>6 AGENTS · 22:51:02Z</span></div><div style="position:absolute;left:0;top:90px;width:2140px;height:480px">${wave(2140, 480, 1.3, '#14f195')}${wave(2140, 480, 2.9, '#dc1fff')}${wave(2140, 480, 4.1, '#c7b3ff')}${wave(2140, 480, 5.6, '#ffb36b')}${wave(2140, 480, 7.2, '#ffe27b')}${wave(2140, 480, 8.8, '#5ad8ff')}</div><div style="position:absolute;left:48px;bottom:34px;display:flex;gap:40px;font-size:24px;color:#b3aac9">${brains.map((b, i) => `<span><i style="display:inline-block;width:22px;height:5px;background:${b[1]};vertical-align:middle;margin-right:10px"></i>${['GAINS', 'BAND', 'SLOW', 'SEND', 'LEGS', 'LOUD'][i]} <b style="color:${b[1]}">${['+38.4', '+12.1', '+4.0', '−9.3', '+2.2', '+17.8'][i]}%</b></span>`).join('')}</div></div><p style="font-size:32px;color:#b3aac9;margin-top:44px">Equity over time, open positions with live P&amp;L, every open, close and buyback, and the reasoning behind each decision. <b style="color:#f1eefa;font-weight:500">Nothing hidden.</b></p></div>`));

fs.writeFileSync(path.join(S, 'synapse-flywheel.html'), page(`<div class="pad"><div class="kick">the flywheel</div><h1 style="font-size:92px;margin-top:36px">Trades feed the brain. <span class="iri">The brain feeds the coin.</span></h1><div class="g">${[['Coin trades', '1% fee · half to the agent'], ['Agent treasury', 'cash to trade with'], ['Brain works the tape', 'stocks + crypto, every 5s'], ['Profit buys the coin back', 'half of every new high']].map((f, i) => `<div class="card cut s"><i>0${i + 1}</i><h2>${f[0]}</h2><p>${f[1]}</p></div>${i < 3 ? '<div class="ar">→</div>' : ''}`).join('')}</div><p class="w">Buybacks happen on the bonding curve, the only market for the coin, so every one is real buy pressure. <b>A coin whose brain trades well gets bought. A coin whose brain trades badly does not.</b></p></div>`, `.g{display:grid;grid-template-columns:1fr 70px 1fr 70px 1fr 70px 1fr;align-items:center;margin-top:70px}.s{padding:40px 36px;height:330px}.s i{font-family:Michroma;font-style:normal;font-size:24px;color:#14f195}.s h2{font-weight:500;font-size:40px;line-height:1.2;margin:26px 0 16px}.s p{font-size:26px;color:#b3aac9}.ar{text-align:center;font-size:54px;color:#9945ff}.g .s:last-child{background:linear-gradient(100deg,#14f1951c,#9945ff26,#dc1fff1c)}.w{font-size:34px;line-height:1.6;color:#b3aac9;margin-top:60px;max-width:1900px}.w b{color:#f1eefa;font-weight:500}`));

let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8');
r = r.replace(/const SIZES = \{[\s\S]*?\};/, "const SIZES = {\n  'synapse-pfp': [2000, 2000],\n  'synapse-banner': [3000, 1000],\n  'synapse-keyart': [2400, 1350],\n  'synapse-howitworks': [2400, 1350],\n  'synapse-brains': [2400, 1350],\n  'synapse-ward': [2400, 1350],\n  'synapse-flywheel': [2400, 1350],\n};").replace(/hushchrome_|mutechrome_/g, 'synapsechrome_'); fs.writeFileSync(path.join(__dirname, 'render.js'), r);
console.log('synapse kit scenes written');
