// SYNAPSE kit, round 2: five new scenes into _studio/src (then: node _studio/render.js <name>)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#14f195"/><stop offset="1" stop-color="#dc1fff"/></linearGradient></defs><g fill="none" stroke-width="2.8" stroke-linecap="round"><path d="M6.6 15.6Q2.6 12.6 3.4 7.4M6.6 24.4Q2.6 27.4 3.4 32.6" stroke="#14f195"/><path d="M33.4 15.6Q37.4 12.6 36.6 7.4M33.4 24.4Q37.4 27.4 36.6 32.6" stroke="#dc1fff"/></g><circle cx="11.2" cy="20" r="6.6" fill="#14f195"/><circle cx="28.8" cy="20" r="6.6" fill="#dc1fff"/><g fill="#f1eefa"><circle cx="20" cy="14.6" r="1.5"/><circle cx="20" cy="20" r="1.9"/><circle cx="20" cy="25.4" r="1.5"/></g></svg>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#776e8f;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#b3aac9}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#f1eefa;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}.card{background:#0c0a14dd;box-shadow:inset 0 0 0 1px #2e2646;position:relative;overflow:hidden}.sub{font-size:30px;color:#b3aac9;line-height:1.5}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}SYNAPSE</b><span>synapsepad.net · @synapsepad · Solana</span></div>`;
const C = { MOMENTUM: '#14f195', REVERSION: '#9945ff', TREND: '#c7b3ff', DEGEN: '#ffb36b', HEDGE: '#ffe27b', VOLHUNT: '#5ad8ff' };
const N = { MOMENTUM: 'MOMENTUM', REVERSION: 'MEAN REVERSION', TREND: 'TREND', DEGEN: 'DEGEN', HEDGE: 'HEDGE', VOLHUNT: 'VOL HUNTER' };

// 1 · real thoughts captured from the six brains on the live tape (2026-10-06)
const TH = [['HEDGE', 'Pair book: long BTC+SOL, short ETH+DOGE. Net exposure zero.'], ['TREND', 'In a 30-day uptrend: SOL +12.8%, ETH +7.5%, BTC +7.0%, DOGE +3.6%. Holding the trend, nothing else.'],
  ['VOLHUNT', 'Loudest tape: DOGE 66% vol, SOL 54% vol, ETH 43% vol, BTC 33% vol. Small bets in the direction of the day.'], ['MOMENTUM', '5-day leaders BTC +1.6%, SOL +0.5%, ETH -0.6%. Long the leaders, short the tail ETH/DOGE.'],
  ['REVERSION', 'Biggest 24h dips DOGE -0.5%, SOL -0.3%, BTC -0.2%. Buying the dip, fading ETH -0.2%.'], ['DEGEN', 'short BTC -0.2%, short ETH -0.2%, short SOL -0.3%. Size: all of it.']];
fs.writeFileSync(path.join(S, 'synapse-thoughts.html'), page(`<div class="pad"><div class="kick">the desk log</div><h1 style="font-size:84px;margin-top:26px">Every coin's brain <span class="iri">thinks out loud.</span></h1>
<div style="margin-top:56px;display:grid;gap:18px">${TH.map(([b, t]) => `<div class="card cut" style="padding:24px 34px;display:grid;grid-template-columns:330px 1fr;align-items:center;gap:20px"><div style="font-family:Michroma;font-size:22px;letter-spacing:.14em;color:${C[b]};display:flex;align-items:center;gap:14px"><i style="width:14px;height:14px;border-radius:50%;background:${C[b]};box-shadow:0 0 14px ${C[b]}"></i>${N[b]}</div><div style="font-family:ui-monospace,Consolas,monospace;font-size:28px;color:#f1eefa">${t}</div></div>`).join('')}</div>
<div style="margin-top:22px;font-size:22px;color:#776e8f">Real entries from the six brains, written against the live tape.</div></div>`));

// 2 · the hard-coded risk rules
const R = [['5s', 'every 5 seconds', 'each brain reads the tape and rebalances'], ['35%', 'max per name', 'no single position bigger than 35% of equity'], ['+12%', 'take profit', 'winners get banked automatically'],
  ['−8%', 'stop loss', 'losers get cut, no hoping'], ['50%', 'of every new high', 'buys the coin back on its curve'], ['1%', 'trade fee', 'half of it goes straight to the agent']];
fs.writeFileSync(path.join(S, 'synapse-rules.html'), page(`<div class="pad"><div class="kick">risk rules</div><h1 style="font-size:96px;margin-top:26px">Discipline, <span class="iri">hard-coded.</span></h1>
<div style="margin-top:64px;display:grid;grid-template-columns:repeat(3,1fr);gap:22px">${R.map(([v, l, d], i) => `<div class="card cut" style="padding:40px 40px 36px;min-height:250px"><div style="font-family:Michroma;font-size:84px;line-height:1" class="${i % 2 ? '' : 'iri'}">${v}</div><div style="font-size:34px;font-weight:600;margin-top:22px">${l}</div><div style="font-size:24px;color:#b3aac9;margin-top:8px">${d}</div></div>`).join('')}</div></div>`));

// 3 · launch flow
const L = [['01', 'Name it', 'pick a name and a ticker'], ['02', 'Pick a brain', 'one of six strategies'], ['03', 'Seed it', 'from 0.2 SOL · 5% launch fee'], ['04', "It's alive", 'the coin, its treasury and its desk go live together']];
fs.writeFileSync(path.join(S, 'synapse-launch.html'), page(`<div class="pad"><div class="kick">launch a coin</div><h1 style="font-size:96px;margin-top:26px">Four steps. <span class="iri">One brain.</span></h1>
<div style="margin-top:80px;display:grid;grid-template-columns:repeat(4,1fr);gap:22px;align-items:stretch">${L.map(([n, t, d], i) => `<div class="card cut" style="padding:54px 44px;min-height:500px${i === 3 ? ';box-shadow:inset 0 0 0 2px #14f195,0 0 60px #14f19533' : ''}"><div style="font-family:Michroma;font-size:26px;color:#776e8f">${n}</div><div style="font-family:Michroma;font-size:54px;text-transform:uppercase;margin-top:30px;line-height:1.15">${t}</div><div style="font-size:32px;color:#b3aac9;margin-top:24px;line-height:1.45">${d}</div></div>`).join('')}</div>
<div class="sub" style="margin-top:46px">From launch, the agent trades the tape and every new high it makes buys the coin back.</div></div>`));

// 4 · normal memecoin vs a SYNAPSE coin
const V = [['Treasury', 'none', 'seeded at launch'], ['Revenue to the coin', 'none', 'half of every 1% trade fee'], ['Does anything', 'no', 'trades 11 markets, every 5s'], ['Buybacks', "only if the dev feels like it", 'automatic: 50% of every new high'], ['What it is thinking', '—', 'every thought and trade, logged in public']];
fs.writeFileSync(path.join(S, 'synapse-vs.html'), page(`<div class="pad"><div class="kick">compared</div><h1 style="font-size:84px;margin-top:26px">A memecoin. <span class="iri">A memecoin with a brain.</span></h1>
<div style="margin-top:60px">
<div style="display:grid;grid-template-columns:1.1fr 1fr 1.25fr;padding:0 0 18px;font-family:Michroma;font-size:24px;letter-spacing:.12em"><div></div><div style="color:#776e8f">MEMECOIN</div><div class="iri">SYNAPSE COIN</div></div>
${V.map(([a, b, c]) => `<div style="display:grid;grid-template-columns:1.1fr 1fr 1.25fr;align-items:center;border-top:1px solid #2e2646;padding:38px 0;font-size:40px"><div style="color:#b3aac9">${a}</div><div style="color:#ff6b8a;font-weight:500">${b}</div><div style="color:#14f195;font-weight:500">${c}</div></div>`).join('')}</div></div>`));

// 5 · the tape
const T = [['SOL', 'crypto'], ['BTC', 'crypto'], ['ETH', 'crypto'], ['DOGE', 'crypto'], ['TSLA', 'stock'], ['NVDA', 'stock'], ['AAPL', 'stock'], ['SPY', 'index'], ['COIN', 'stock'], ['MSTR', 'stock'], ['GLD', 'gold']];
fs.writeFileSync(path.join(S, 'synapse-tape.html'), page(`<div class="pad"><div class="kick">what the brains trade</div><h1 style="font-size:96px;margin-top:26px">Eleven markets. <span class="iri">Six brains.</span></h1>
<div style="margin-top:64px;display:grid;grid-template-columns:repeat(6,1fr);gap:18px">${T.map(([s, k], i) => `<div class="card cut" style="padding:58px 28px;text-align:center${i < 4 ? ';box-shadow:inset 0 0 0 1px #14f19566' : ''}"><div style="font-family:Michroma;font-size:58px">${s}</div><div style="font-size:22px;color:#776e8f;margin-top:12px;letter-spacing:.14em;text-transform:uppercase">${k}</div></div>`).join('')}<div class="card cut" style="padding:58px 28px;text-align:center;box-shadow:inset 0 0 0 2px #9945ff"><div style="font-family:Michroma;font-size:58px" class="iri">LIVE</div><div style="font-size:22px;color:#776e8f;margin-top:12px;letter-spacing:.14em">THE TAPE</div></div></div>
<div class="sub" style="margin-top:48px">Crypto, megacap stocks, the index and gold, priced off the live tape. Each brain reads all of it and picks its own book.</div></div>`));
console.log('wrote 5 scenes');
