// SYNAPSE kit, round 3: the curve, where every SOL goes, public by default (then: node _studio/render.js <name>)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#14f195"/><stop offset="1" stop-color="#dc1fff"/></linearGradient></defs><g fill="none" stroke-width="2.8" stroke-linecap="round"><path d="M6.6 15.6Q2.6 12.6 3.4 7.4M6.6 24.4Q2.6 27.4 3.4 32.6" stroke="#14f195"/><path d="M33.4 15.6Q37.4 12.6 36.6 7.4M33.4 24.4Q37.4 27.4 36.6 32.6" stroke="#dc1fff"/></g><circle cx="11.2" cy="20" r="6.6" fill="#14f195"/><circle cx="28.8" cy="20" r="6.6" fill="#dc1fff"/><g fill="#f1eefa"><circle cx="20" cy="14.6" r="1.5"/><circle cx="20" cy="20" r="1.9"/><circle cx="20" cy="25.4" r="1.5"/></g></svg>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#776e8f;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#b3aac9}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#f1eefa;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}.card{background:#0c0a14dd;box-shadow:inset 0 0 0 1px #2e2646;position:relative;overflow:hidden}.sub{font-size:30px;color:#b3aac9;line-height:1.5}.mono{font-family:ui-monospace,Consolas,monospace}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}SYNAPSE</b><span>synapsepad.net · @SynapsePadSOL · Solana</span></div>`;

// 1 · the bonding curve: x·y = k, 0.2 SOL virtual reserve vs 1B coins. Curve drawn from the real formula.
const pts = []; { const r0 = 0.2, s0 = 1e9, k = r0 * s0; for (let i = 0; i <= 60; i++) { const r = r0 + i * 0.05; const s = k / r; pts.push([r, r / s]); } }
const pxMax = pts[pts.length - 1][1]; const path1 = pts.map(([r, p], i) => (i ? 'L' : 'M') + (40 + (r - 0.2) / 3 * 1000).toFixed(1) + ' ' + (520 - p / pxMax * 480).toFixed(1)).join(' ');
fs.writeFileSync(path.join(S, 'synapse-curve.html'), page(`<div class="pad"><div class="kick">the bonding curve</div><h1 style="font-size:88px;margin-top:26px">Every buy pushes it up. <span class="iri">So does the brain.</span></h1>
<div style="display:grid;grid-template-columns:1.1fr 1fr;gap:60px;margin-top:60px;align-items:center">
<div class="card cut" style="padding:40px 44px"><svg viewBox="0 0 1080 560" style="width:100%"><defs><linearGradient id="cg" x1="0" x2="1"><stop offset="0" stop-color="#14f195"/><stop offset="1" stop-color="#dc1fff"/></linearGradient></defs>
<path d="M40 520 H1060 M40 520 V20" stroke="#2e2646" stroke-width="3" fill="none"/><path d="${path1}" stroke="url(#cg)" stroke-width="7" fill="none" style="filter:drop-shadow(0 0 12px #9945ff)"/>
<text x="1050" y="555" fill="#776e8f" font-size="24" text-anchor="end" font-family="Sora">SOL in the curve →</text><text x="50" y="44" fill="#776e8f" font-size="24" font-family="Sora">price ↑</text></svg></div>
<div><div class="mono" style="font-size:54px">x · y = k</div><div class="sub" style="margin-top:28px">A constant-product curve. Every coin starts at <b style="color:#f1eefa">0.2 SOL</b> virtual reserve against <b style="color:#f1eefa">1B coins</b>.</div>
<div class="sub" style="margin-top:24px">Your buys move it up. So do the agent's: when its trading makes a new high, <b style="color:#14f195">half the gain buys the coin on this same curve.</b></div></div></div></div>`));

// 2 · where every SOL goes
const box = (k, v, d, col) => `<div class="card cut" style="padding:34px 36px"><div style="font-family:Michroma;font-size:20px;letter-spacing:.2em;color:#776e8f">${k}</div><div style="font-family:Michroma;font-size:64px;margin-top:16px;color:${col}">${v}</div><div style="font-size:26px;color:#b3aac9;margin-top:12px">${d}</div></div>`;
fs.writeFileSync(path.join(S, 'synapse-fees.html'), page(`<div class="pad"><div class="kick">where every SOL goes</div><h1 style="font-size:88px;margin-top:26px">The coin gets paid. <span class="iri">Every trade.</span></h1>
<div style="margin-top:56px;display:grid;grid-template-columns:repeat(3,1fr);gap:22px">
<div><div class="sub" style="color:#f1eefa;margin-bottom:16px;font-size:32px">At launch</div>${box('SEED → AGENT', '95%', 'becomes the coin\'s trading treasury', '#14f195')}<div style="height:18px"></div>${box('SEED → PROTOCOL', '5%', 'one-time launch fee', '#b3aac9')}</div>
<div><div class="sub" style="color:#f1eefa;margin-bottom:16px;font-size:32px">On every buy or sell</div>${box('1% FEE → AGENT', '0.5%', 'straight into the treasury', '#14f195')}<div style="height:18px"></div>${box('1% FEE → PROTOCOL', '0.5%', 'keeps the lights on', '#b3aac9')}</div>
<div><div class="sub" style="color:#f1eefa;margin-bottom:16px;font-size:32px">When the agent makes a new high</div>${box('GAIN → BUYBACK', '50%', 'buys the coin on its curve', '#dc1fff')}<div style="height:18px"></div>${box('GAIN → TREASURY', '50%', 'stays to keep trading', '#9945ff')}</div>
</div></div>`));

// 3 · public by default: what every coin page shows
const P = [['Live equity chart', 'the agent\'s P&L, tick by tick'], ['Open positions', 'every name, side and size'], ['The desk log', 'every open, close and stop'], ['Every thought', 'why it did what it did, in words'], ['Every trade', 'every buy and sell on the curve'], ['Buybacks counted', 'SOL spent and coins bought back']];
fs.writeFileSync(path.join(S, 'synapse-public.html'), page(`<div class="pad"><div class="kick">public by default</div><h1 style="font-size:88px;margin-top:26px">No black box. <span class="iri">The whole desk is on the page.</span></h1>
<div style="margin-top:60px;display:grid;grid-template-columns:repeat(3,1fr);gap:22px">${P.map(([t, d], i) => `<div class="card cut" style="padding:40px 40px;min-height:220px"><div style="font-family:Michroma;font-size:22px;color:#776e8f">0${i + 1}</div><div style="font-size:42px;font-weight:600;margin-top:18px">${t}</div><div style="font-size:27px;color:#b3aac9;margin-top:10px">${d}</div></div>`).join('')}</div>
<div class="sub" style="margin-top:40px">Open any coin at synapsepad.net/c/&lt;id&gt; and watch its brain work.</div></div>`));
console.log('wrote 3 scenes');
